### ISSUE TITLE
asciinema on mobile

### ISSUE THREAD

**Issue by zlee-personal** [willghatch/rash-lang.org#1]
I found some time to make some improvements to the website, like having mobile not just be a smaller version of the desktop site.  Unfortunately, asciinema is unable to responsively change it's column number, so when the screen width is too small the characters just run off into nothing.  I was thinking of either messing with the js for the player to make it work or maybe translating the video to code examples in the website, whichever you prefer.

**Comment by willghatch** [comment]
Thanks for your help with all this!  Sorry for the delayed reply.

I really prefer it as a video instead of just code examples on a page.
I feel like the live video somehow says more forcefully that it is a
real shell that works and is usable than static examples would.

Does this new design not allow the full window to just fit in the
frame?  Currently I think the video looks great on my phone.  Honestly
I like the site on mobile as it is now, and I hate those mobile sites
that can't have the zoom adjusted and can't display everything
properly.  Do you already have code for this?  Would you make a PR
instead of just an issue so I can look at it?

In other words, I already like the site you made so much!  Maybe I'm
just afraid of change.  But I definitely want to see what you've done.
Maybe I can re-do the demo in a smaller window that would be more
mobile-friendly.

That said, I've been thinking about the website myself lately.  I've
lately felt galvanized to *actually* work on the documentation updates
I've been promising forever.  In addition to updating the written
documentation, There is a ~20 minute presentation I've done a couple
versions of to live audiences that has never been properly recorded
for web hosting.  I've been thinking I should re-work it into a few
5-10 minute video presentations to put on the website (or link to from
the website, more likely).  So design changes aside, the website
should have some new content soon.  (Where soon could be within a few
weeks or in a few months.)

**Comment by zlee-personal** [comment]
It's nothing to concrete so far.  After watching a few YouTube videos, I discovered that if you add a `<meta name="viewport" content="width=device-width, initial-scale=1.0">`, it makes the mobile site go from 
![image](https://user-images.githubusercontent.com/10042016/61338127-523bfd00-a7f5-11e9-8757-25208b30295b.png)
to 
![image](https://user-images.githubusercontent.com/10042016/61338167-80b9d800-a7f5-11e9-8578-16b47ce3c84d.png)
which seems to look much more mobile-like.  The only real thing I've added so far is to make a little drop down menu at the top when the screen width gets too small.  There's a few existing problems on mobile you can see if you go to full screen mode, it cuts about half of the video off.  But if you want to keep the video I'm sure there's some way to fix it.

**Comment by zlee-personal** [comment]
I'll make a pr so we can discuss it there
